services:
  mysql:
    container_name: 'MySQL_db'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=reminderDB'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=rt'
    ports:
      - '3306:3306'